[platformio]
default_envs = ttgo-t-display

[env:ttgo-t-display]
platform = espressif32
board = lilygo-t-display
framework = arduino
monitor_speed = 115200
build_flags =
  -DUSE_MOCK_SENSOR=1
lib_deps =
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  adafruit/Adafruit GFX Library @ ^1.11.11
